"""Added a constraint to profile table

Revision ID: 1f7c263ae185
Revises: c7a3c28f46ed
Create Date: 2026-09-03 22:15:48.526034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7c263ae185'
down_revision: Union[str, Sequence[str], None] = 'c7a3c28f46ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('enforce_single_row', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'profile', ['enforce_single_row'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_column('profile', 'enforce_single_row')
    # ### end Alembic commands ###
