"""Second migration

Revision ID: 21c52097d308
Revises: 79fe5a45fcf0
Create Date: 2026-09-02 00:36:04.440707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c52097d308'
down_revision: Union[str, Sequence[str], None] = '79fe5a45fcf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('enforce_single_row', sa.Integer(), nullable=False),
    sa.CheckConstraint('enforce_single_row = 1', name='only_one_admin_allowed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('enforce_single_row')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'skills', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'testimonial', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testimonial', type_='foreignkey')
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
