"""project_type field added to testimonial

Revision ID: 2b16a5d7f18a
Revises: ebf4e53bfd5e
Create Date: 2026-09-11 23:00:32.432214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b16a5d7f18a'
down_revision: Union[str, Sequence[str], None] = 'ebf4e53bfd5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testimonials', sa.Column('project_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testimonials', 'project_type')
    # ### end Alembic commands ###
