"""Removed rating field

Revision ID: 5589263742d4
Revises: 7f32904e4d3f
Create Date: 2026-09-10 13:21:06.212059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5589263742d4'
down_revision: Union[str, Sequence[str], None] = '7f32904e4d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_image', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testimonials_id'), 'testimonials', ['id'], unique=True)
    op.drop_index(op.f('ix_testimonial_id'), table_name='testimonial')
    op.drop_table('testimonial')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonial',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('testimonial_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('testimonial_pkey'))
    )
    op.create_index(op.f('ix_testimonial_id'), 'testimonial', ['id'], unique=True)
    op.drop_index(op.f('ix_testimonials_id'), table_name='testimonials')
    op.drop_table('testimonials')
    # ### end Alembic commands ###
