"""Added check_constraint column to user

Revision ID: 79fe5a45fcf0
Revises: 3c24820a5ca0
Create Date: 2026-09-01 23:32:47.538272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79fe5a45fcf0'
down_revision: Union[str, Sequence[str], None] = '3c24820a5ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('enforce_single_row', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['enforce_single_row'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'enforce_single_row')
    # ### end Alembic commands ###
