"""removed purpose column from token verification table

Revision ID: 8eac7ca8b1ba
Revises: b0f448d4a74b
Create Date: 2026-09-02 01:11:10.524563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eac7ca8b1ba'
down_revision: Union[str, Sequence[str], None] = 'b0f448d4a74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_tokens', 'purpose')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_tokens', sa.Column('purpose', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
