"""Message column added to message model

Revision ID: 9f5560150d3d
Revises: 2b16a5d7f18a
Create Date: 2026-09-17 11:56:28.955549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5560150d3d'
down_revision: Union[str, Sequence[str], None] = '2b16a5d7f18a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_message', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sender_message')
    # ### end Alembic commands ###
