"""Added a new column to verification token table

Revision ID: c7a3c28f46ed
Revises: 8eac7ca8b1ba
Create Date: 2026-09-02 02:56:32.840955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a3c28f46ed'
down_revision: Union[str, Sequence[str], None] = '8eac7ca8b1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_tokens', sa.Column('otp_attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_tokens', 'otp_attempts')
    # ### end Alembic commands ###
